CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`source` enum('general','subprime','prime') NOT NULL DEFAULT 'general',
	`status` enum('New','Contacted','Converted','Archived') NOT NULL DEFAULT 'New',
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(30) NOT NULL,
	`dateOfBirth` varchar(20),
	`address` text,
	`city` varchar(100),
	`state` varchar(50),
	`zipCode` varchar(20),
	`employmentStatus` varchar(50),
	`employerName` varchar(150),
	`jobTitle` varchar(100),
	`yearsEmployed` varchar(20),
	`monthlyIncome` varchar(30),
	`payFrequency` varchar(30),
	`additionalIncome` varchar(30),
	`vehicleType` varchar(50),
	`preferredMake` varchar(100),
	`preferredModel` varchar(100),
	`maxBudget` varchar(30),
	`downPayment` varchar(30),
	`tradeIn` varchar(10),
	`creditScoreRange` varchar(50),
	`hasBankruptcy` varchar(10),
	`bankruptcyDischargeDate` varchar(30),
	`hasRepossession` varchar(10),
	`hasCoApplicant` varchar(10),
	`coApplicantName` varchar(200),
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
